### ISSUE TITLE
Income Statement Not Picking up Quarter data on income statement

### ISSUE THREAD

**Issue by jdy214** [dgunning/edgartools#86] opened 2024-08-13 19:57 UTC
Hello,

I do not know if it is by design.  Can work around if it is.  For the 3rd Quarter Income Statements, we are only able to pull the 9 month tables and not the 3 month tables.  So I am assuming if you want information regarding that quarter the only way is to subtract the Q1 and Q2 data?  Would be nice if we could pick up the 4 tables in the income statement in the Q3 financial documents

**Comment by dgunning** [comment] 2024-08-13 20:10
This is not by design. Some quarterly reports have 6 months as well as 9 months and it requires extra logic to distinguish the tables. I previously patched the edge case for the 6 months, so could extend the logic for 9 months

Give me an example and I will look into it

**Comment by jdy214** [comment] 2024-08-13 20:22
If you look at Appfolio (APPF) any of the 3rd quarter statements like 10Q
for September 2023.

Very Truly,
Justin

**Comment by dgunning** [comment] 2024-08-14 20:34
Added a fix and new tests. Should pick up the 3, 6 and 9 months in the next release

https://github.com/dgunning/edgartools/blob/cbe5793167990864fa5a70d274754b44122f7e8d/tests/test_xbrl_financials.py#L269

**Comment by dgunning** [comment] 2024-08-14 20:49
Should be fixed in 2.27.11, just released

**Comment by jdy214** [comment] 2024-08-14 21:08
Incredible!

I'm curious as a user how would you suggest compensating for the change in
taxonomy over time. Like a given company can use several different labels
for revenue over a 10 year period. Is the right way to download the
taxonomy for all.periods and map them to common term?

Are you planning to also.make the supplemental tables and schedules
accessible. I noticed some are available but other populate with keywords
but not values.

Really  a wonderful tool

Justin

**Comment by dgunning** [comment] 2024-08-15 00:37
What do you mean by supplemental tables and schedules.

You can get a list of statements from the `XBRLData` object.  The API is a work in progress so any suggestion about what needs to be made easier is welcome

See documentation

<img width="360" alt="statements" src="https://github.com/user-attachments/assets/4d5ecd45-2433-4323-8d25-f1b6def1c802">


https://github.com/dgunning/edgartools/wiki/ParsingXBRL#the-statements-object

**Comment by dgunning** [comment] 2024-08-15 13:07
For the other part of your question about the change in taxonomy see if you can use the raw concepts as they change less frequently than the labels.

```python
income_statement.get_dataframe(include_concept=True)
```

**Comment by jdy214** [comment] 2024-08-16 18:12
Hi Dwight,

I did as you suggested you are right the concepts are far more stable,
unfortunately i could only find the Taxonomy files going back to 2021 as
xls files, but this will be far better moving forward to aggregate years of
data.

What I meant earlier about the supplement tables are the notes
following the consolidated financial statements.  It was sporadic regarding
whether the fields had data or not.  I was curious if you noticed this as
well?

**Comment by jdy214** [comment] 2024-08-20 00:49
Hi Dwight,

So I was able to make good use of the concepts.  I see that some companies
have concepts with a prefix that are company specific.  Tesla for instance
has tsla_Government_GrantReceipt.  How are these prefixes being generated
since they arent part of the SEC's taxonomy?

Very Truly,
Justin

**Comment by dgunning** [comment] 2024-08-20 02:25
The Tesla XBRL file declares the Tesla taxonomy at the top of the file. As far as XBRL is concerned the TSLA and SEC taxonomies are on par with each other
```xml
<xbrl xmlns="http://www.xbrl.org/2003/instance" 
xmlns:country="http://xbrl.sec.gov/country/2023" 
xmlns:dei="http://xbrl.sec.gov/dei/2023"
xmlns:ecd="http://xbrl.sec.gov/ecd/2023" 
xmlns:exch="http://xbrl.sec.gov/exch/2023" 
xmlns:iso4217="http://www.xbrl.org/2003/iso4217"
xmlns:link="http://www.xbrl.org/2003/linkbase" 
xmlns:srt="http://fasb.org/srt/2023" 
xmlns:tsla="http://www.tesla.com/20240630" 
xmlns:us-gaap="http://fasb.org/us-gaap/2023" 
xmlns:xbrldi="http://xbrl.org/2006/xbrldi" 
xmlns:xlink="http://www.w3.org/1999/xlink" 
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xml:lang="en-US">
```

The prefixes are inside the document like `'tsla:Government_GrantReceipt'` the code replaces `':'` with `'_'`

**Comment by dgunning** [comment] 2024-08-20 23:12
Fixed.

**Closed by dgunning** 2024-08-20 23:12 UTC
Labels: bug
