### ISSUE TITLE
get_filings error

### ISSUE THREAD

**Issue by jmdelay** [dgunning/edgartools#172] opened 2024-12-23 22:20 UTC
fils = get_filings(year=list(range(2006,2023)))

>> ArrowInvalid: Failed to parse string: 'ER  8206' as a scalar of type int32

**Comment by kevander** [comment] 2024-12-24 00:09
having the same issue when I call "get_by_accession_number"

**Comment by alberttangalbert** [comment] 2024-12-24 05:20
the problem is coming from the `read_fixed_width_index` function in `edgar/_filings.py`

this is a revised version of the function that works:
'''
def read_fixed_width_index(index_text: str, file_specs: FileSpecs) -> pa.Table:
    """
    Read the index text as a fixed-width file.
    :param index_text: The index text as downloaded from SEC Edgar.
    :param file_specs: The file specs containing the column definitions.
    :return: A PyArrow Table.
    """
    # Treat as a single array
    lines = index_text.rstrip('\n').split('\n')
    
    # Find where the data starts
    data_start = 0
    for index, line in enumerate(lines):
        if line.startswith("-----"):
            data_start = index + 1
            break
    data_lines = lines[data_start:]
    array = pa.array(data_lines)

    # Then split into separate arrays by file specs
    arrays = [
        pc.utf8_trim_whitespace(
            pc.utf8_slice_codeunits(array, start=start, stop=stop))
        for start, stop,
        in file_specs.splits
    ]

    # Sanitize and convert CIK to int
    def sanitize_to_int32(arr):
        sanitized = []
        for value in arr.to_pylist():
            try:
                sanitized.append(int(value))
            except ValueError:
                sanitized.append(None)  # Replace invalid values with None
        return pa.array(sanitized, type=pa.int32())

    arrays[2] = sanitize_to_int32(arrays[2])

    # Convert filingdate from string to date
    # Handle multiple date formats
    def parse_dates(arr, date_format1='%Y-%m-%d', date_format2='%Y%m%d'):
        result = []
        for value in arr.to_pylist():
            try:
                if len(value) == 10:
                    result.append(pc.strptime(value, date_format1, 'us').as_py())
                else:
                    result.append(pc.strptime(value, date_format2, 'us').as_py())
            except Exception:
                result.append(None)  # Replace invalid dates with None
        return pa.array(result, type=pa.date32())

    arrays[3] = parse_dates(arrays[3])

    # Get the accession number from the file directory_or_file
    arrays[4] = pa.compute.utf8_slice_codeunits(
        pa.compute.utf8_rtrim(arrays[4], characters=".txt"), start=-20
    )

    # Create a PyArrow Table
    return pa.Table.from_arrays(
        arrays=arrays,
        names=list(file_specs.schema.names),
    )
'''

**Comment by dgunning** [comment] 2024-12-24 14:50
This was a critical data bug fixed in **3.4.1** that unfortunately broke all versions before that. So update to at least 3.4.1

Friday night the SEC change the name of a company in all their index files to 

**"UNITED PLANNERS' FINANCIAL SERVICES OF AMERICA A LIMITED PARTNER"** which broke my fixed width parser.
So I had to retire the fixed width parser which performed flawlessly the past 2 years.

I'm going to figure out a way to do alerts for critical issues like this.

<img width="690" alt="UnitedPlanners" src="https://github.com/user-attachments/assets/4f8605af-542c-4fe2-b890-4c087a90b1dd" />

**Comment by tom-flamelit** [comment] 2024-12-24 15:42
Consider an incrementally increasing limit on the fixed width, say by 10
characters at a time? Try/Catch with a max size could be feasible?

BTW, love this project, easily the best Pythpn/SEC integration I've come
across.

**Comment by kevander** [comment] 2024-12-24 16:13
thanks for the quick fix!

**Closed** 2024-12-27 14:15 UTC
Labels: bug
