### ISSUE TITLE
[bug/feature] fetch latest filings

### ISSUE THREAD

**Issue by edwardsun** [dgunning/edgartools#11] opened 2023-08-23 15:05 UTC
Hi,

I‘m recently trying to see if it is possible to fetch latest data via edgartools. 
eg. I was looking at https://www.sec.gov/cgi-bin/browse-edgar?company=&CIK=&type=4&owner=only&count=40&action=getcurrent
and try to get the latest records with exact accepted date time. However, it seems edgartools' most recent records only went up to "yesterday" not "today". I also tried edgar.get_by_accession_number but cannot find a specific "today's" record.

Would it be possible to achieve "live" records fetching using edgartools?

Thank you for the great tool.

**Comment by dgunning** [comment] 2023-08-26 15:21
By design the library only accesses filings that are in the latest filing indexes, meaning for the latest day for which data is available, only filings before the 5:30PM cutoff will be included. 

To implement the get_current call to get the post-cutoff filings will be a feature. Likely it will be a separate api call e.g. get_current_filings. If this turns out to ge easy to implement, then it may be merged into get_filings, and get_by_accession_number, but I won't know until I start.

I will look at this next week

**Comment by dgunning** [comment] 2023-09-18 15:24
Add get_current_filings in 2.1.0. Will improve with cik and other filters in future minor releases

**Closed by dgunning** 2023-09-18 15:24 UTC
